/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureapplicationgatewayloaddistributionpolicy/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AzureApplicationGatewayLoadDistributionPolicyLister helps list AzureApplicationGatewayLoadDistributionPolicies.
// All objects returned here must be treated as read-only.
type AzureApplicationGatewayLoadDistributionPolicyLister interface {
	// List lists all AzureApplicationGatewayLoadDistributionPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.AzureApplicationGatewayLoadDistributionPolicy, err error)
	// AzureApplicationGatewayLoadDistributionPolicies returns an object that can list and get AzureApplicationGatewayLoadDistributionPolicies.
	AzureApplicationGatewayLoadDistributionPolicies(namespace string) AzureApplicationGatewayLoadDistributionPolicyNamespaceLister
	AzureApplicationGatewayLoadDistributionPolicyListerExpansion
}

// azureApplicationGatewayLoadDistributionPolicyLister implements the AzureApplicationGatewayLoadDistributionPolicyLister interface.
type azureApplicationGatewayLoadDistributionPolicyLister struct {
	indexer cache.Indexer
}

// NewAzureApplicationGatewayLoadDistributionPolicyLister returns a new AzureApplicationGatewayLoadDistributionPolicyLister.
func NewAzureApplicationGatewayLoadDistributionPolicyLister(indexer cache.Indexer) AzureApplicationGatewayLoadDistributionPolicyLister {
	return &azureApplicationGatewayLoadDistributionPolicyLister{indexer: indexer}
}

// List lists all AzureApplicationGatewayLoadDistributionPolicies in the indexer.
func (s *azureApplicationGatewayLoadDistributionPolicyLister) List(selector labels.Selector) (ret []*v1beta1.AzureApplicationGatewayLoadDistributionPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.AzureApplicationGatewayLoadDistributionPolicy))
	})
	return ret, err
}

// AzureApplicationGatewayLoadDistributionPolicies returns an object that can list and get AzureApplicationGatewayLoadDistributionPolicies.
func (s *azureApplicationGatewayLoadDistributionPolicyLister) AzureApplicationGatewayLoadDistributionPolicies(namespace string) AzureApplicationGatewayLoadDistributionPolicyNamespaceLister {
	return azureApplicationGatewayLoadDistributionPolicyNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AzureApplicationGatewayLoadDistributionPolicyNamespaceLister helps list and get AzureApplicationGatewayLoadDistributionPolicies.
// All objects returned here must be treated as read-only.
type AzureApplicationGatewayLoadDistributionPolicyNamespaceLister interface {
	// List lists all AzureApplicationGatewayLoadDistributionPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.AzureApplicationGatewayLoadDistributionPolicy, err error)
	// Get retrieves the AzureApplicationGatewayLoadDistributionPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.AzureApplicationGatewayLoadDistributionPolicy, error)
	AzureApplicationGatewayLoadDistributionPolicyNamespaceListerExpansion
}

// azureApplicationGatewayLoadDistributionPolicyNamespaceLister implements the AzureApplicationGatewayLoadDistributionPolicyNamespaceLister
// interface.
type azureApplicationGatewayLoadDistributionPolicyNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AzureApplicationGatewayLoadDistributionPolicies in the indexer for a given namespace.
func (s azureApplicationGatewayLoadDistributionPolicyNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.AzureApplicationGatewayLoadDistributionPolicy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.AzureApplicationGatewayLoadDistributionPolicy))
	})
	return ret, err
}

// Get retrieves the AzureApplicationGatewayLoadDistributionPolicy from the indexer for a given namespace and name.
func (s azureApplicationGatewayLoadDistributionPolicyNamespaceLister) Get(name string) (*v1beta1.AzureApplicationGatewayLoadDistributionPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("azureapplicationgatewayloaddistributionpolicy"), name)
	}
	return obj.(*v1beta1.AzureApplicationGatewayLoadDistributionPolicy), nil
}
