// -------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// --------------------------------------------------------------------------------------------

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +genclient:nonNamespaced

// AzureApplicationGatewayInstanceUpdateStatus is the resource AGIC is watching on for the status of Application Gateway instances update backend addresses
type AzureApplicationGatewayInstanceUpdateStatus struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +optional
	Spec AzureApplicationGatewayInstanceUpdateStatusSpec `json:"spec"`
}

// AzureApplicationGatewayInstanceUpdateStatusSpec defines a list of backend pool addresses
type AzureApplicationGatewayInstanceUpdateStatusSpec struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// InstanceID identifies instance
	InstanceID string `json:"instanceID,omitempty"`

	// InstanceCount indicates the total count of Application Gateway instances
	InstanceCount int32 `json:"instanceCount,omitempty"`

	// DesiredBackendPoolResourceVersion indicates the desired version of backend address pool crd object Application Gateway instances to apply
	DesiredBackendPoolResourceVersion string `json:"desiredBackendPoolResourceVersion,omitempty"`

	// CurrentBackendPoolResourceVersion indicates the current version of backend address pool crd object Application Gateway instances applied
	CurrentBackendPoolResourceVersion string `json:"currentBackendPoolResourceVersion,omitempty"`

	// LastCheckInTime records the last check-in time by Application Gateway instance
	LastCheckInTime string `json:"lastCheckInTime,omitempty"`

	// +optional
	// ErroCode generated by Application Gateway instances when fail to update backend pool addresses
	ErrorCode string `json:"errorCode,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// AzureApplicationGatewayInstanceUpdateStatusList is the list of instance update status on backend pool addresses
type AzureApplicationGatewayInstanceUpdateStatusList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []AzureApplicationGatewayInstanceUpdateStatus `json:"items"`
}
