/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"

	azureapplicationgatewayinstanceupdatestatusv1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureapplicationgatewayinstanceupdatestatus/v1beta1"
	versioned "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/clientset/versioned"
	internalinterfaces "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/listers/azureapplicationgatewayinstanceupdatestatus/v1beta1"
)

// AzureApplicationGatewayInstanceUpdateStatusInformer provides access to a shared informer and lister for
// AzureApplicationGatewayInstanceUpdateStatuses.
type AzureApplicationGatewayInstanceUpdateStatusInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.AzureApplicationGatewayInstanceUpdateStatusLister
}

type azureApplicationGatewayInstanceUpdateStatusInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewAzureApplicationGatewayInstanceUpdateStatusInformer constructs a new informer for AzureApplicationGatewayInstanceUpdateStatus type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAzureApplicationGatewayInstanceUpdateStatusInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAzureApplicationGatewayInstanceUpdateStatusInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAzureApplicationGatewayInstanceUpdateStatusInformer constructs a new informer for AzureApplicationGatewayInstanceUpdateStatus type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAzureApplicationGatewayInstanceUpdateStatusInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzureapplicationgatewayinstanceupdatestatusV1beta1().AzureApplicationGatewayInstanceUpdateStatuses().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzureapplicationgatewayinstanceupdatestatusV1beta1().AzureApplicationGatewayInstanceUpdateStatuses().Watch(context.TODO(), options)
			},
		},
		&azureapplicationgatewayinstanceupdatestatusv1beta1.AzureApplicationGatewayInstanceUpdateStatus{},
		resyncPeriod,
		indexers,
	)
}

func (f *azureApplicationGatewayInstanceUpdateStatusInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAzureApplicationGatewayInstanceUpdateStatusInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *azureApplicationGatewayInstanceUpdateStatusInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&azureapplicationgatewayinstanceupdatestatusv1beta1.AzureApplicationGatewayInstanceUpdateStatus{}, f.defaultInformer)
}

func (f *azureApplicationGatewayInstanceUpdateStatusInformer) Lister() v1beta1.AzureApplicationGatewayInstanceUpdateStatusLister {
	return v1beta1.NewAzureApplicationGatewayInstanceUpdateStatusLister(f.Informer().GetIndexer())
}
