# We are going to run the build in a container. 
# The reason we run the build in a container is that we have dependency on protobuf when we are building on Linux. 
# Building protobuf as a build step is quite time consuming, so we want to package the protobuf as a container image with all the dependencies captured and run the build within this container.
sudo: required
language: c
services:
    - docker

script:
  - cd $TRAVIS_BUILD_DIR
  - chmod u+x scripts/*
  - mkdir build
  - cd build
  - IMAGE_VERSION=${TRAVIS_TAG:-latest}
  - cmake .. -Ddeployment_push_prefix="$ACR_REGISTRY" 
              -Ddeployment_image_name="public/azure-application-gateway/kubernetes-ingress" 
              -Ddeployment_image_version="$IMAGE_VERSION" 
  - cmake --build .
  
deploy:
  provider: script
  skip_cleanup: true
  script:
    - echo "$DOCKER_PASSWORD" | docker login $ACR_REGISTRY -u "$DOCKER_USERNAME" --password-stdin
    - cd $TRAVIS_BUILD_DIR/build && cmake --build . --target dockerpush
  on:
    repo: Azure/application-gateway-kubernetes-ingress
    tags: true
    branch: master
