/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureingressallowedtarget/v1"
	scheme "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/clientset/versioned/scheme"
)

// AzureIngressAllowedTargetsGetter has a method to return a AzureIngressAllowedTargetInterface.
// A group's client should implement this interface.
type AzureIngressAllowedTargetsGetter interface {
	AzureIngressAllowedTargets(namespace string) AzureIngressAllowedTargetInterface
}

// AzureIngressAllowedTargetInterface has methods to work with AzureIngressAllowedTarget resources.
type AzureIngressAllowedTargetInterface interface {
	Create(ctx context.Context, azureIngressAllowedTarget *v1.AzureIngressAllowedTarget, opts metav1.CreateOptions) (*v1.AzureIngressAllowedTarget, error)
	Update(ctx context.Context, azureIngressAllowedTarget *v1.AzureIngressAllowedTarget, opts metav1.UpdateOptions) (*v1.AzureIngressAllowedTarget, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.AzureIngressAllowedTarget, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.AzureIngressAllowedTargetList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AzureIngressAllowedTarget, err error)
	AzureIngressAllowedTargetExpansion
}

// azureIngressAllowedTargets implements AzureIngressAllowedTargetInterface
type azureIngressAllowedTargets struct {
	client rest.Interface
	ns     string
}

// newAzureIngressAllowedTargets returns a AzureIngressAllowedTargets
func newAzureIngressAllowedTargets(c *AzureingressallowedtargetsV1Client, namespace string) *azureIngressAllowedTargets {
	return &azureIngressAllowedTargets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the azureIngressAllowedTarget, and returns the corresponding azureIngressAllowedTarget object, and an error if there is any.
func (c *azureIngressAllowedTargets) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.AzureIngressAllowedTarget, err error) {
	result = &v1.AzureIngressAllowedTarget{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azureingressallowedtargets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzureIngressAllowedTargets that match those selectors.
func (c *azureIngressAllowedTargets) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AzureIngressAllowedTargetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AzureIngressAllowedTargetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azureingressallowedtargets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azureIngressAllowedTargets.
func (c *azureIngressAllowedTargets) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("azureingressallowedtargets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a azureIngressAllowedTarget and creates it.  Returns the server's representation of the azureIngressAllowedTarget, and an error, if there is any.
func (c *azureIngressAllowedTargets) Create(ctx context.Context, azureIngressAllowedTarget *v1.AzureIngressAllowedTarget, opts metav1.CreateOptions) (result *v1.AzureIngressAllowedTarget, err error) {
	result = &v1.AzureIngressAllowedTarget{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("azureingressallowedtargets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azureIngressAllowedTarget).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a azureIngressAllowedTarget and updates it. Returns the server's representation of the azureIngressAllowedTarget, and an error, if there is any.
func (c *azureIngressAllowedTargets) Update(ctx context.Context, azureIngressAllowedTarget *v1.AzureIngressAllowedTarget, opts metav1.UpdateOptions) (result *v1.AzureIngressAllowedTarget, err error) {
	result = &v1.AzureIngressAllowedTarget{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azureingressallowedtargets").
		Name(azureIngressAllowedTarget.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azureIngressAllowedTarget).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the azureIngressAllowedTarget and deletes it. Returns an error if one occurs.
func (c *azureIngressAllowedTargets) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azureingressallowedtargets").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azureIngressAllowedTargets) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azureingressallowedtargets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched azureIngressAllowedTarget.
func (c *azureIngressAllowedTargets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AzureIngressAllowedTarget, err error) {
	result = &v1.AzureIngressAllowedTarget{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("azureingressallowedtargets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
