/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureapplicationgatewayrewrite/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAzureApplicationGatewayRewrites implements AzureApplicationGatewayRewriteInterface
type FakeAzureApplicationGatewayRewrites struct {
	Fake *FakeAzureapplicationgatewayrewritesV1beta1
}

var azureapplicationgatewayrewritesResource = schema.GroupVersionResource{Group: "azureapplicationgatewayrewrites.appgw.ingress.azure.io", Version: "v1beta1", Resource: "azureapplicationgatewayrewrites"}

var azureapplicationgatewayrewritesKind = schema.GroupVersionKind{Group: "azureapplicationgatewayrewrites.appgw.ingress.azure.io", Version: "v1beta1", Kind: "AzureApplicationGatewayRewrite"}

// Get takes name of the azureApplicationGatewayRewrite, and returns the corresponding azureApplicationGatewayRewrite object, and an error if there is any.
func (c *FakeAzureApplicationGatewayRewrites) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.AzureApplicationGatewayRewrite, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(azureapplicationgatewayrewritesResource, name), &v1beta1.AzureApplicationGatewayRewrite{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AzureApplicationGatewayRewrite), err
}

// List takes label and field selectors, and returns the list of AzureApplicationGatewayRewrites that match those selectors.
func (c *FakeAzureApplicationGatewayRewrites) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.AzureApplicationGatewayRewriteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(azureapplicationgatewayrewritesResource, azureapplicationgatewayrewritesKind, opts), &v1beta1.AzureApplicationGatewayRewriteList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.AzureApplicationGatewayRewriteList{ListMeta: obj.(*v1beta1.AzureApplicationGatewayRewriteList).ListMeta}
	for _, item := range obj.(*v1beta1.AzureApplicationGatewayRewriteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureApplicationGatewayRewrites.
func (c *FakeAzureApplicationGatewayRewrites) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(azureapplicationgatewayrewritesResource, opts))
}

// Create takes the representation of a azureApplicationGatewayRewrite and creates it.  Returns the server's representation of the azureApplicationGatewayRewrite, and an error, if there is any.
func (c *FakeAzureApplicationGatewayRewrites) Create(ctx context.Context, azureApplicationGatewayRewrite *v1beta1.AzureApplicationGatewayRewrite, opts v1.CreateOptions) (result *v1beta1.AzureApplicationGatewayRewrite, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(azureapplicationgatewayrewritesResource, azureApplicationGatewayRewrite), &v1beta1.AzureApplicationGatewayRewrite{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AzureApplicationGatewayRewrite), err
}

// Update takes the representation of a azureApplicationGatewayRewrite and updates it. Returns the server's representation of the azureApplicationGatewayRewrite, and an error, if there is any.
func (c *FakeAzureApplicationGatewayRewrites) Update(ctx context.Context, azureApplicationGatewayRewrite *v1beta1.AzureApplicationGatewayRewrite, opts v1.UpdateOptions) (result *v1beta1.AzureApplicationGatewayRewrite, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(azureapplicationgatewayrewritesResource, azureApplicationGatewayRewrite), &v1beta1.AzureApplicationGatewayRewrite{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AzureApplicationGatewayRewrite), err
}

// Delete takes name of the azureApplicationGatewayRewrite and deletes it. Returns an error if one occurs.
func (c *FakeAzureApplicationGatewayRewrites) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(azureapplicationgatewayrewritesResource, name), &v1beta1.AzureApplicationGatewayRewrite{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureApplicationGatewayRewrites) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(azureapplicationgatewayrewritesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.AzureApplicationGatewayRewriteList{})
	return err
}

// Patch applies the patch and returns the patched azureApplicationGatewayRewrite.
func (c *FakeAzureApplicationGatewayRewrites) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.AzureApplicationGatewayRewrite, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(azureapplicationgatewayrewritesResource, name, pt, data, subresources...), &v1beta1.AzureApplicationGatewayRewrite{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AzureApplicationGatewayRewrite), err
}
