/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	v1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azurebackendpool/v1"
)

// AzureBackendPoolLister helps list AzureBackendPools.
type AzureBackendPoolLister interface {
	// List lists all AzureBackendPools in the indexer.
	List(selector labels.Selector) (ret []*v1.AzureBackendPool, err error)
	// Get retrieves the AzureBackendPool from the index for a given name.
	Get(name string) (*v1.AzureBackendPool, error)
	AzureBackendPoolListerExpansion
}

// azureBackendPoolLister implements the AzureBackendPoolLister interface.
type azureBackendPoolLister struct {
	indexer cache.Indexer
}

// NewAzureBackendPoolLister returns a new AzureBackendPoolLister.
func NewAzureBackendPoolLister(indexer cache.Indexer) AzureBackendPoolLister {
	return &azureBackendPoolLister{indexer: indexer}
}

// List lists all AzureBackendPools in the indexer.
func (s *azureBackendPoolLister) List(selector labels.Selector) (ret []*v1.AzureBackendPool, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AzureBackendPool))
	})
	return ret, err
}

// Get retrieves the AzureBackendPool from the index for a given name.
func (s *azureBackendPoolLister) Get(name string) (*v1.AzureBackendPool, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("azurebackendpool"), name)
	}
	return obj.(*v1.AzureBackendPool), nil
}
