appgw:
  subscriptionId: 86501df2-2fc5-4fc3-b193-d305572e416f
  resourceGroup: <resource group>
  name: <application gateway>

armAuth:
  type: aadPodIdentity
  identityResourceID: <user assigned identity for application gateway ingress controller>
  identityClientID:  <user assigned identity client Id.>