/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureapplicationgatewayloaddistributionpolicy/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAzureApplicationGatewayLoadDistributionPolicies implements AzureApplicationGatewayLoadDistributionPolicyInterface
type FakeAzureApplicationGatewayLoadDistributionPolicies struct {
	Fake *FakeAzureapplicationgatewayloaddistributionpoliciesV1beta1
	ns   string
}

var azureapplicationgatewayloaddistributionpoliciesResource = schema.GroupVersionResource{Group: "azureapplicationgatewayloaddistributionpolicies.appgw.ingress.azure.io", Version: "v1beta1", Resource: "azureapplicationgatewayloaddistributionpolicies"}

var azureapplicationgatewayloaddistributionpoliciesKind = schema.GroupVersionKind{Group: "azureapplicationgatewayloaddistributionpolicies.appgw.ingress.azure.io", Version: "v1beta1", Kind: "AzureApplicationGatewayLoadDistributionPolicy"}

// Get takes name of the azureApplicationGatewayLoadDistributionPolicy, and returns the corresponding azureApplicationGatewayLoadDistributionPolicy object, and an error if there is any.
func (c *FakeAzureApplicationGatewayLoadDistributionPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.AzureApplicationGatewayLoadDistributionPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azureapplicationgatewayloaddistributionpoliciesResource, c.ns, name), &v1beta1.AzureApplicationGatewayLoadDistributionPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AzureApplicationGatewayLoadDistributionPolicy), err
}

// List takes label and field selectors, and returns the list of AzureApplicationGatewayLoadDistributionPolicies that match those selectors.
func (c *FakeAzureApplicationGatewayLoadDistributionPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.AzureApplicationGatewayLoadDistributionPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azureapplicationgatewayloaddistributionpoliciesResource, azureapplicationgatewayloaddistributionpoliciesKind, c.ns, opts), &v1beta1.AzureApplicationGatewayLoadDistributionPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.AzureApplicationGatewayLoadDistributionPolicyList{ListMeta: obj.(*v1beta1.AzureApplicationGatewayLoadDistributionPolicyList).ListMeta}
	for _, item := range obj.(*v1beta1.AzureApplicationGatewayLoadDistributionPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureApplicationGatewayLoadDistributionPolicies.
func (c *FakeAzureApplicationGatewayLoadDistributionPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azureapplicationgatewayloaddistributionpoliciesResource, c.ns, opts))

}

// Create takes the representation of a azureApplicationGatewayLoadDistributionPolicy and creates it.  Returns the server's representation of the azureApplicationGatewayLoadDistributionPolicy, and an error, if there is any.
func (c *FakeAzureApplicationGatewayLoadDistributionPolicies) Create(ctx context.Context, azureApplicationGatewayLoadDistributionPolicy *v1beta1.AzureApplicationGatewayLoadDistributionPolicy, opts v1.CreateOptions) (result *v1beta1.AzureApplicationGatewayLoadDistributionPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azureapplicationgatewayloaddistributionpoliciesResource, c.ns, azureApplicationGatewayLoadDistributionPolicy), &v1beta1.AzureApplicationGatewayLoadDistributionPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AzureApplicationGatewayLoadDistributionPolicy), err
}

// Update takes the representation of a azureApplicationGatewayLoadDistributionPolicy and updates it. Returns the server's representation of the azureApplicationGatewayLoadDistributionPolicy, and an error, if there is any.
func (c *FakeAzureApplicationGatewayLoadDistributionPolicies) Update(ctx context.Context, azureApplicationGatewayLoadDistributionPolicy *v1beta1.AzureApplicationGatewayLoadDistributionPolicy, opts v1.UpdateOptions) (result *v1beta1.AzureApplicationGatewayLoadDistributionPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azureapplicationgatewayloaddistributionpoliciesResource, c.ns, azureApplicationGatewayLoadDistributionPolicy), &v1beta1.AzureApplicationGatewayLoadDistributionPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AzureApplicationGatewayLoadDistributionPolicy), err
}

// Delete takes name of the azureApplicationGatewayLoadDistributionPolicy and deletes it. Returns an error if one occurs.
func (c *FakeAzureApplicationGatewayLoadDistributionPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(azureapplicationgatewayloaddistributionpoliciesResource, c.ns, name), &v1beta1.AzureApplicationGatewayLoadDistributionPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureApplicationGatewayLoadDistributionPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azureapplicationgatewayloaddistributionpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.AzureApplicationGatewayLoadDistributionPolicyList{})
	return err
}

// Patch applies the patch and returns the patched azureApplicationGatewayLoadDistributionPolicy.
func (c *FakeAzureApplicationGatewayLoadDistributionPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.AzureApplicationGatewayLoadDistributionPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azureapplicationgatewayloaddistributionpoliciesResource, c.ns, name, pt, data, subresources...), &v1beta1.AzureApplicationGatewayLoadDistributionPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AzureApplicationGatewayLoadDistributionPolicy), err
}
