# This shows a setup for Blue/Green deployment
---
apiVersion: appgw.ingress.azure.io/v1beta1
kind: AzureApplicationGatewayLoadDistribitionPolicy
metadata:
  name: load-distribution-policy-blue-green
  targets:
    - backend:
        service:
          name: old-service
          port:
            number: 80
      role: active
      weight: 8
    - backend:
        service:
          name: new-service
          port:
            number: 80
      role: passive
      weight: 2
