apiVersion: appgw.ingress.azure.io/v1beta1
kind: AzureApplicationGatewayRewrite
metadata:
  name: test-crd
spec:
  rewriteRules:
  - name: test-rewrite-rule
    
    ruleSequence: 100

    conditions:
    - ignoreCase: true
      negate: false
      variable: keep-alive
      pattern: keep-alive
                            
    actions:
      requestHeaderConfigurations:
      - actionType: set
        headerName: custom-header1
        headerValue: value1
      - actionType: set
        headerName: custom-header2
        headerValue: value2
        
      responseHeaderConfigurations:
      - actionType: set
        headerName: custom-header3
        headerValue: value3
      - actionType: set
        headerName: custom-header3
        headerValue: value3
        
      urlConfiguration:
        modifiedPath: "/api/"
        modifiedQueryString: "query=test-value"
        reroute: false