/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	azureingressallowedtargetv1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureingressallowedtarget/v1"
)

// FakeAzureIngressAllowedTargets implements AzureIngressAllowedTargetInterface
type FakeAzureIngressAllowedTargets struct {
	Fake *FakeAzureingressallowedtargetsV1
	ns   string
}

var azureingressallowedtargetsResource = schema.GroupVersionResource{Group: "azureingressallowedtargets.appgw.ingress.k8s.io", Version: "v1", Resource: "azureingressallowedtargets"}

var azureingressallowedtargetsKind = schema.GroupVersionKind{Group: "azureingressallowedtargets.appgw.ingress.k8s.io", Version: "v1", Kind: "AzureIngressAllowedTarget"}

// Get takes name of the azureIngressAllowedTarget, and returns the corresponding azureIngressAllowedTarget object, and an error if there is any.
func (c *FakeAzureIngressAllowedTargets) Get(ctx context.Context, name string, options v1.GetOptions) (result *azureingressallowedtargetv1.AzureIngressAllowedTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azureingressallowedtargetsResource, c.ns, name), &azureingressallowedtargetv1.AzureIngressAllowedTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azureingressallowedtargetv1.AzureIngressAllowedTarget), err
}

// List takes label and field selectors, and returns the list of AzureIngressAllowedTargets that match those selectors.
func (c *FakeAzureIngressAllowedTargets) List(ctx context.Context, opts v1.ListOptions) (result *azureingressallowedtargetv1.AzureIngressAllowedTargetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azureingressallowedtargetsResource, azureingressallowedtargetsKind, c.ns, opts), &azureingressallowedtargetv1.AzureIngressAllowedTargetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &azureingressallowedtargetv1.AzureIngressAllowedTargetList{ListMeta: obj.(*azureingressallowedtargetv1.AzureIngressAllowedTargetList).ListMeta}
	for _, item := range obj.(*azureingressallowedtargetv1.AzureIngressAllowedTargetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureIngressAllowedTargets.
func (c *FakeAzureIngressAllowedTargets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azureingressallowedtargetsResource, c.ns, opts))

}

// Create takes the representation of a azureIngressAllowedTarget and creates it.  Returns the server's representation of the azureIngressAllowedTarget, and an error, if there is any.
func (c *FakeAzureIngressAllowedTargets) Create(ctx context.Context, azureIngressAllowedTarget *azureingressallowedtargetv1.AzureIngressAllowedTarget, opts v1.CreateOptions) (result *azureingressallowedtargetv1.AzureIngressAllowedTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azureingressallowedtargetsResource, c.ns, azureIngressAllowedTarget), &azureingressallowedtargetv1.AzureIngressAllowedTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azureingressallowedtargetv1.AzureIngressAllowedTarget), err
}

// Update takes the representation of a azureIngressAllowedTarget and updates it. Returns the server's representation of the azureIngressAllowedTarget, and an error, if there is any.
func (c *FakeAzureIngressAllowedTargets) Update(ctx context.Context, azureIngressAllowedTarget *azureingressallowedtargetv1.AzureIngressAllowedTarget, opts v1.UpdateOptions) (result *azureingressallowedtargetv1.AzureIngressAllowedTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azureingressallowedtargetsResource, c.ns, azureIngressAllowedTarget), &azureingressallowedtargetv1.AzureIngressAllowedTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azureingressallowedtargetv1.AzureIngressAllowedTarget), err
}

// Delete takes name of the azureIngressAllowedTarget and deletes it. Returns an error if one occurs.
func (c *FakeAzureIngressAllowedTargets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(azureingressallowedtargetsResource, c.ns, name), &azureingressallowedtargetv1.AzureIngressAllowedTarget{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureIngressAllowedTargets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azureingressallowedtargetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &azureingressallowedtargetv1.AzureIngressAllowedTargetList{})
	return err
}

// Patch applies the patch and returns the patched azureIngressAllowedTarget.
func (c *FakeAzureIngressAllowedTargets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *azureingressallowedtargetv1.AzureIngressAllowedTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azureingressallowedtargetsResource, c.ns, name, pt, data, subresources...), &azureingressallowedtargetv1.AzureIngressAllowedTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azureingressallowedtargetv1.AzureIngressAllowedTarget), err
}
