/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	azureingressmanagedtargetv1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureingressmanagedtarget/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAzureIngressManagedTargets implements AzureIngressManagedTargetInterface
type FakeAzureIngressManagedTargets struct {
	Fake *FakeAzureingressmanagedtargetsV1
	ns   string
}

var azureingressmanagedtargetsResource = schema.GroupVersionResource{Group: "azureingressmanagedtargets.appgw.ingress.k8s.io", Version: "v1", Resource: "azureingressmanagedtargets"}

var azureingressmanagedtargetsKind = schema.GroupVersionKind{Group: "azureingressmanagedtargets.appgw.ingress.k8s.io", Version: "v1", Kind: "AzureIngressManagedTarget"}

// Get takes name of the azureIngressManagedTarget, and returns the corresponding azureIngressManagedTarget object, and an error if there is any.
func (c *FakeAzureIngressManagedTargets) Get(name string, options v1.GetOptions) (result *azureingressmanagedtargetv1.AzureIngressManagedTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azureingressmanagedtargetsResource, c.ns, name), &azureingressmanagedtargetv1.AzureIngressManagedTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azureingressmanagedtargetv1.AzureIngressManagedTarget), err
}

// List takes label and field selectors, and returns the list of AzureIngressManagedTargets that match those selectors.
func (c *FakeAzureIngressManagedTargets) List(opts v1.ListOptions) (result *azureingressmanagedtargetv1.AzureIngressManagedTargetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azureingressmanagedtargetsResource, azureingressmanagedtargetsKind, c.ns, opts), &azureingressmanagedtargetv1.AzureIngressManagedTargetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &azureingressmanagedtargetv1.AzureIngressManagedTargetList{ListMeta: obj.(*azureingressmanagedtargetv1.AzureIngressManagedTargetList).ListMeta}
	for _, item := range obj.(*azureingressmanagedtargetv1.AzureIngressManagedTargetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureIngressManagedTargets.
func (c *FakeAzureIngressManagedTargets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azureingressmanagedtargetsResource, c.ns, opts))

}

// Create takes the representation of a azureIngressManagedTarget and creates it.  Returns the server's representation of the azureIngressManagedTarget, and an error, if there is any.
func (c *FakeAzureIngressManagedTargets) Create(azureIngressManagedTarget *azureingressmanagedtargetv1.AzureIngressManagedTarget) (result *azureingressmanagedtargetv1.AzureIngressManagedTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azureingressmanagedtargetsResource, c.ns, azureIngressManagedTarget), &azureingressmanagedtargetv1.AzureIngressManagedTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azureingressmanagedtargetv1.AzureIngressManagedTarget), err
}

// Update takes the representation of a azureIngressManagedTarget and updates it. Returns the server's representation of the azureIngressManagedTarget, and an error, if there is any.
func (c *FakeAzureIngressManagedTargets) Update(azureIngressManagedTarget *azureingressmanagedtargetv1.AzureIngressManagedTarget) (result *azureingressmanagedtargetv1.AzureIngressManagedTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azureingressmanagedtargetsResource, c.ns, azureIngressManagedTarget), &azureingressmanagedtargetv1.AzureIngressManagedTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azureingressmanagedtargetv1.AzureIngressManagedTarget), err
}

// Delete takes name of the azureIngressManagedTarget and deletes it. Returns an error if one occurs.
func (c *FakeAzureIngressManagedTargets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(azureingressmanagedtargetsResource, c.ns, name), &azureingressmanagedtargetv1.AzureIngressManagedTarget{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureIngressManagedTargets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azureingressmanagedtargetsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &azureingressmanagedtargetv1.AzureIngressManagedTargetList{})
	return err
}

// Patch applies the patch and returns the patched azureIngressManagedTarget.
func (c *FakeAzureIngressManagedTargets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *azureingressmanagedtargetv1.AzureIngressManagedTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azureingressmanagedtargetsResource, c.ns, name, pt, data, subresources...), &azureingressmanagedtargetv1.AzureIngressManagedTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*azureingressmanagedtargetv1.AzureIngressManagedTarget), err
}
