/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureapplicationgatewaybackendpool/v1beta1"
	scheme "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/clientset/versioned/scheme"
)

// AzureApplicationGatewayBackendPoolsGetter has a method to return a AzureApplicationGatewayBackendPoolInterface.
// A group's client should implement this interface.
type AzureApplicationGatewayBackendPoolsGetter interface {
	AzureApplicationGatewayBackendPools() AzureApplicationGatewayBackendPoolInterface
}

// AzureApplicationGatewayBackendPoolInterface has methods to work with AzureApplicationGatewayBackendPool resources.
type AzureApplicationGatewayBackendPoolInterface interface {
	Create(*v1beta1.AzureApplicationGatewayBackendPool) (*v1beta1.AzureApplicationGatewayBackendPool, error)
	Update(*v1beta1.AzureApplicationGatewayBackendPool) (*v1beta1.AzureApplicationGatewayBackendPool, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.AzureApplicationGatewayBackendPool, error)
	List(opts v1.ListOptions) (*v1beta1.AzureApplicationGatewayBackendPoolList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.AzureApplicationGatewayBackendPool, err error)
	AzureApplicationGatewayBackendPoolExpansion
}

// azureApplicationGatewayBackendPools implements AzureApplicationGatewayBackendPoolInterface
type azureApplicationGatewayBackendPools struct {
	client rest.Interface
}

// newAzureApplicationGatewayBackendPools returns a AzureApplicationGatewayBackendPools
func newAzureApplicationGatewayBackendPools(c *AzureapplicationgatewaybackendpoolsV1beta1Client) *azureApplicationGatewayBackendPools {
	return &azureApplicationGatewayBackendPools{
		client: c.RESTClient(),
	}
}

// Get takes name of the azureApplicationGatewayBackendPool, and returns the corresponding azureApplicationGatewayBackendPool object, and an error if there is any.
func (c *azureApplicationGatewayBackendPools) Get(name string, options v1.GetOptions) (result *v1beta1.AzureApplicationGatewayBackendPool, err error) {
	result = &v1beta1.AzureApplicationGatewayBackendPool{}
	err = c.client.Get().
		Resource("azureapplicationgatewaybackendpools").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzureApplicationGatewayBackendPools that match those selectors.
func (c *azureApplicationGatewayBackendPools) List(opts v1.ListOptions) (result *v1beta1.AzureApplicationGatewayBackendPoolList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.AzureApplicationGatewayBackendPoolList{}
	err = c.client.Get().
		Resource("azureapplicationgatewaybackendpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azureApplicationGatewayBackendPools.
func (c *azureApplicationGatewayBackendPools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("azureapplicationgatewaybackendpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a azureApplicationGatewayBackendPool and creates it.  Returns the server's representation of the azureApplicationGatewayBackendPool, and an error, if there is any.
func (c *azureApplicationGatewayBackendPools) Create(azureApplicationGatewayBackendPool *v1beta1.AzureApplicationGatewayBackendPool) (result *v1beta1.AzureApplicationGatewayBackendPool, err error) {
	result = &v1beta1.AzureApplicationGatewayBackendPool{}
	err = c.client.Post().
		Resource("azureapplicationgatewaybackendpools").
		Body(azureApplicationGatewayBackendPool).
		Do().
		Into(result)
	return
}

// Update takes the representation of a azureApplicationGatewayBackendPool and updates it. Returns the server's representation of the azureApplicationGatewayBackendPool, and an error, if there is any.
func (c *azureApplicationGatewayBackendPools) Update(azureApplicationGatewayBackendPool *v1beta1.AzureApplicationGatewayBackendPool) (result *v1beta1.AzureApplicationGatewayBackendPool, err error) {
	result = &v1beta1.AzureApplicationGatewayBackendPool{}
	err = c.client.Put().
		Resource("azureapplicationgatewaybackendpools").
		Name(azureApplicationGatewayBackendPool.Name).
		Body(azureApplicationGatewayBackendPool).
		Do().
		Into(result)
	return
}

// Delete takes name of the azureApplicationGatewayBackendPool and deletes it. Returns an error if one occurs.
func (c *azureApplicationGatewayBackendPools) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("azureapplicationgatewaybackendpools").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azureApplicationGatewayBackendPools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("azureapplicationgatewaybackendpools").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched azureApplicationGatewayBackendPool.
func (c *azureApplicationGatewayBackendPools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.AzureApplicationGatewayBackendPool, err error) {
	result = &v1beta1.AzureApplicationGatewayBackendPool{}
	err = c.client.Patch(pt).
		Resource("azureapplicationgatewaybackendpools").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
