{{- if required "A valid armAuth entry is required!" .Values.armAuth }}
{{- end}}
{{- if eq .Values.armAuth.type "aadPodIdentity"}}

# Please see https://github.com/Azure/aad-pod-identity for more inromation
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ template "application-gateway-kubernetes-ingress.azureidentity" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: 0
  ResourceID: {{ required "armAuth.identityResourceID is required if using AAD-Pod-Identity" .Values.armAuth.identityResourceID }}
  ClientID: {{ required "armAuth.identityClientID is required if using AAD-Pod-Identity" .Values.armAuth.identityClientID }}

{{- end}}