{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "application-gateway-kubernetes-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "application-gateway-kubernetes-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
    - endpoints
    - pods
    - secrets
    - namespaces
    - services
    - events
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - extensions
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - extensions
  resources:
    - ingresses/status
  verbs:
    - update
{{- end -}}