/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureapplicationgatewayheaderrewrite/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AzureApplicationGatewayHeaderRewriteLister helps list AzureApplicationGatewayHeaderRewrites.
// All objects returned here must be treated as read-only.
type AzureApplicationGatewayHeaderRewriteLister interface {
	// List lists all AzureApplicationGatewayHeaderRewrites in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.AzureApplicationGatewayHeaderRewrite, err error)
	// Get retrieves the AzureApplicationGatewayHeaderRewrite from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.AzureApplicationGatewayHeaderRewrite, error)
	AzureApplicationGatewayHeaderRewriteListerExpansion
}

// azureApplicationGatewayHeaderRewriteLister implements the AzureApplicationGatewayHeaderRewriteLister interface.
type azureApplicationGatewayHeaderRewriteLister struct {
	indexer cache.Indexer
}

// NewAzureApplicationGatewayHeaderRewriteLister returns a new AzureApplicationGatewayHeaderRewriteLister.
func NewAzureApplicationGatewayHeaderRewriteLister(indexer cache.Indexer) AzureApplicationGatewayHeaderRewriteLister {
	return &azureApplicationGatewayHeaderRewriteLister{indexer: indexer}
}

// List lists all AzureApplicationGatewayHeaderRewrites in the indexer.
func (s *azureApplicationGatewayHeaderRewriteLister) List(selector labels.Selector) (ret []*v1beta1.AzureApplicationGatewayHeaderRewrite, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.AzureApplicationGatewayHeaderRewrite))
	})
	return ret, err
}

// Get retrieves the AzureApplicationGatewayHeaderRewrite from the index for a given name.
func (s *azureApplicationGatewayHeaderRewriteLister) Get(name string) (*v1beta1.AzureApplicationGatewayHeaderRewrite, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("azureapplicationgatewayheaderrewrite"), name)
	}
	return obj.(*v1beta1.AzureApplicationGatewayHeaderRewrite), nil
}
