/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureapplicationgatewayinstanceupdatestatus/v1beta1"
	scheme "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AzureApplicationGatewayInstanceUpdateStatusesGetter has a method to return a AzureApplicationGatewayInstanceUpdateStatusInterface.
// A group's client should implement this interface.
type AzureApplicationGatewayInstanceUpdateStatusesGetter interface {
	AzureApplicationGatewayInstanceUpdateStatuses() AzureApplicationGatewayInstanceUpdateStatusInterface
}

// AzureApplicationGatewayInstanceUpdateStatusInterface has methods to work with AzureApplicationGatewayInstanceUpdateStatus resources.
type AzureApplicationGatewayInstanceUpdateStatusInterface interface {
	Create(ctx context.Context, azureApplicationGatewayInstanceUpdateStatus *v1beta1.AzureApplicationGatewayInstanceUpdateStatus, opts v1.CreateOptions) (*v1beta1.AzureApplicationGatewayInstanceUpdateStatus, error)
	Update(ctx context.Context, azureApplicationGatewayInstanceUpdateStatus *v1beta1.AzureApplicationGatewayInstanceUpdateStatus, opts v1.UpdateOptions) (*v1beta1.AzureApplicationGatewayInstanceUpdateStatus, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.AzureApplicationGatewayInstanceUpdateStatus, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.AzureApplicationGatewayInstanceUpdateStatusList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.AzureApplicationGatewayInstanceUpdateStatus, err error)
	AzureApplicationGatewayInstanceUpdateStatusExpansion
}

// azureApplicationGatewayInstanceUpdateStatuses implements AzureApplicationGatewayInstanceUpdateStatusInterface
type azureApplicationGatewayInstanceUpdateStatuses struct {
	client rest.Interface
}

// newAzureApplicationGatewayInstanceUpdateStatuses returns a AzureApplicationGatewayInstanceUpdateStatuses
func newAzureApplicationGatewayInstanceUpdateStatuses(c *AzureapplicationgatewayinstanceupdatestatusV1beta1Client) *azureApplicationGatewayInstanceUpdateStatuses {
	return &azureApplicationGatewayInstanceUpdateStatuses{
		client: c.RESTClient(),
	}
}

// Get takes name of the azureApplicationGatewayInstanceUpdateStatus, and returns the corresponding azureApplicationGatewayInstanceUpdateStatus object, and an error if there is any.
func (c *azureApplicationGatewayInstanceUpdateStatuses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.AzureApplicationGatewayInstanceUpdateStatus, err error) {
	result = &v1beta1.AzureApplicationGatewayInstanceUpdateStatus{}
	err = c.client.Get().
		Resource("azureapplicationgatewayinstanceupdatestatuses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzureApplicationGatewayInstanceUpdateStatuses that match those selectors.
func (c *azureApplicationGatewayInstanceUpdateStatuses) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.AzureApplicationGatewayInstanceUpdateStatusList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.AzureApplicationGatewayInstanceUpdateStatusList{}
	err = c.client.Get().
		Resource("azureapplicationgatewayinstanceupdatestatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azureApplicationGatewayInstanceUpdateStatuses.
func (c *azureApplicationGatewayInstanceUpdateStatuses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("azureapplicationgatewayinstanceupdatestatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a azureApplicationGatewayInstanceUpdateStatus and creates it.  Returns the server's representation of the azureApplicationGatewayInstanceUpdateStatus, and an error, if there is any.
func (c *azureApplicationGatewayInstanceUpdateStatuses) Create(ctx context.Context, azureApplicationGatewayInstanceUpdateStatus *v1beta1.AzureApplicationGatewayInstanceUpdateStatus, opts v1.CreateOptions) (result *v1beta1.AzureApplicationGatewayInstanceUpdateStatus, err error) {
	result = &v1beta1.AzureApplicationGatewayInstanceUpdateStatus{}
	err = c.client.Post().
		Resource("azureapplicationgatewayinstanceupdatestatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azureApplicationGatewayInstanceUpdateStatus).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a azureApplicationGatewayInstanceUpdateStatus and updates it. Returns the server's representation of the azureApplicationGatewayInstanceUpdateStatus, and an error, if there is any.
func (c *azureApplicationGatewayInstanceUpdateStatuses) Update(ctx context.Context, azureApplicationGatewayInstanceUpdateStatus *v1beta1.AzureApplicationGatewayInstanceUpdateStatus, opts v1.UpdateOptions) (result *v1beta1.AzureApplicationGatewayInstanceUpdateStatus, err error) {
	result = &v1beta1.AzureApplicationGatewayInstanceUpdateStatus{}
	err = c.client.Put().
		Resource("azureapplicationgatewayinstanceupdatestatuses").
		Name(azureApplicationGatewayInstanceUpdateStatus.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azureApplicationGatewayInstanceUpdateStatus).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the azureApplicationGatewayInstanceUpdateStatus and deletes it. Returns an error if one occurs.
func (c *azureApplicationGatewayInstanceUpdateStatuses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("azureapplicationgatewayinstanceupdatestatuses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azureApplicationGatewayInstanceUpdateStatuses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("azureapplicationgatewayinstanceupdatestatuses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched azureApplicationGatewayInstanceUpdateStatus.
func (c *azureApplicationGatewayInstanceUpdateStatuses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.AzureApplicationGatewayInstanceUpdateStatus, err error) {
	result = &v1beta1.AzureApplicationGatewayInstanceUpdateStatus{}
	err = c.client.Patch(pt).
		Resource("azureapplicationgatewayinstanceupdatestatuses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
