/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	azureapplicationgatewayheaderrewritev1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureapplicationgatewayheaderrewrite/v1beta1"
	versioned "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/clientset/versioned"
	internalinterfaces "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/listers/azureapplicationgatewayheaderrewrite/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AzureApplicationGatewayHeaderRewriteInformer provides access to a shared informer and lister for
// AzureApplicationGatewayHeaderRewrites.
type AzureApplicationGatewayHeaderRewriteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.AzureApplicationGatewayHeaderRewriteLister
}

type azureApplicationGatewayHeaderRewriteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewAzureApplicationGatewayHeaderRewriteInformer constructs a new informer for AzureApplicationGatewayHeaderRewrite type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAzureApplicationGatewayHeaderRewriteInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAzureApplicationGatewayHeaderRewriteInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAzureApplicationGatewayHeaderRewriteInformer constructs a new informer for AzureApplicationGatewayHeaderRewrite type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAzureApplicationGatewayHeaderRewriteInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzureapplicationgatewayheaderrewriteV1beta1().AzureApplicationGatewayHeaderRewrites().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzureapplicationgatewayheaderrewriteV1beta1().AzureApplicationGatewayHeaderRewrites().Watch(context.TODO(), options)
			},
		},
		&azureapplicationgatewayheaderrewritev1beta1.AzureApplicationGatewayHeaderRewrite{},
		resyncPeriod,
		indexers,
	)
}

func (f *azureApplicationGatewayHeaderRewriteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAzureApplicationGatewayHeaderRewriteInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *azureApplicationGatewayHeaderRewriteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&azureapplicationgatewayheaderrewritev1beta1.AzureApplicationGatewayHeaderRewrite{}, f.defaultInformer)
}

func (f *azureApplicationGatewayHeaderRewriteInformer) Lister() v1beta1.AzureApplicationGatewayHeaderRewriteLister {
	return v1beta1.NewAzureApplicationGatewayHeaderRewriteLister(f.Informer().GetIndexer())
}
