apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition 
metadata: 
  name: azureapplicationgatewaybackendpools.appgw.ingress.azure.io 
spec: 
  group: appgw.ingress.azure.io 
  version: v1beta1
  scope: Cluster 
  names: 
    plural: azureapplicationgatewaybackendpools 
    singular: azureapplicationgatewaybackendpool 
    kind: AzureApplicationGatewayBackendPool 
    shortNames: 
    - agpool 
  validation: 
    openAPIV3Schema: 
      type: object 
      properties: 
        spec: 
          type: object 
          properties: 
            backendAddressPools: 
              description: "A list of Application Gateway backend pools" 
              type: array 
              items: 
                type: object 
                properties: 
                  name: 
                    description: "Name of the Application Gateway backend pool" 
                    type: string 
                  backendAddresses: 
                    description: "A list of backend pool addresses" 
                    type: array 
                    items: 
                      type: object 
                      properties: 
                        ipAddress: 
                          description: "ipv4 address" 
                          type: string 