apiVersion: apiextensions.k8s.io/v1 
kind: CustomResourceDefinition 
metadata: 
  name: azureapplicationgatewayinstanceupdatestatuses.appgw.ingress.azure.io 
spec: 
  group: appgw.ingress.azure.io 
  versions: 
    - name: v1beta1 
      served: true 
      storage: true 
      schema: 
        openAPIV3Schema: 
          type: object 
          properties: 
            spec: 
              properties: 
                instanceID:
                  description: "Application Gateway Instance unique ID"
                  type: string
                instanceCount:
                  description: "The total count of Application Gateway Instances"
                  type: integer
                desiredBackendPoolResourceVersion:
                  description: "Disired Backend Pool Resource Version Applied by Application Gateway Instance"
                  type: string
                currentAppliedBackendPoolResourceVersion:
                  description: "Current Backend Pool Resource Version Applied by Application Gateway Instance"
                  type: string
                lastCheckInTime:
                  description: "The Last Timestamp the Application Gateway Instance Checks in the InstanceUpdateStatus CRD Object"
                  type: string
                errorCode:
                  description: "(optional) Error Code to Indicate Instance Update Status Failure"
                  type: string       
  scope: Cluster 
  names: 
    plural: azureapplicationgatewayinstanceupdatestatuses
    singular: azureapplicationgatewayinstanceupdatestatus
    kind: AzureApplicationGatewayInstanceUpdateStatus
    shortNames: 
    - aginst