# Please see https://github.com/Azure/aad-pod-identity for more inromation
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: azure-identity-appgw-ingress          # will be used by aadpodidbinding.yaml
spec:
  type: 0
  ResourceID: "/subscriptions/<subscription-id>/resourceGroups/<mc-resourcegroup-name>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identity-name>"
  ClientID: "<identity-client-id>"