/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	azureapplicationgatewayloaddistributionpolicyv1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureapplicationgatewayloaddistributionpolicy/v1beta1"
	versioned "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/clientset/versioned"
	internalinterfaces "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/listers/azureapplicationgatewayloaddistributionpolicy/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AzureApplicationGatewayLoadDistributionPolicyInformer provides access to a shared informer and lister for
// AzureApplicationGatewayLoadDistributionPolicies.
type AzureApplicationGatewayLoadDistributionPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.AzureApplicationGatewayLoadDistributionPolicyLister
}

type azureApplicationGatewayLoadDistributionPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAzureApplicationGatewayLoadDistributionPolicyInformer constructs a new informer for AzureApplicationGatewayLoadDistributionPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAzureApplicationGatewayLoadDistributionPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAzureApplicationGatewayLoadDistributionPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAzureApplicationGatewayLoadDistributionPolicyInformer constructs a new informer for AzureApplicationGatewayLoadDistributionPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAzureApplicationGatewayLoadDistributionPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzureapplicationgatewayloaddistributionpoliciesV1beta1().AzureApplicationGatewayLoadDistributionPolicies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzureapplicationgatewayloaddistributionpoliciesV1beta1().AzureApplicationGatewayLoadDistributionPolicies(namespace).Watch(context.TODO(), options)
			},
		},
		&azureapplicationgatewayloaddistributionpolicyv1beta1.AzureApplicationGatewayLoadDistributionPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *azureApplicationGatewayLoadDistributionPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAzureApplicationGatewayLoadDistributionPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *azureApplicationGatewayLoadDistributionPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&azureapplicationgatewayloaddistributionpolicyv1beta1.AzureApplicationGatewayLoadDistributionPolicy{}, f.defaultInformer)
}

func (f *azureApplicationGatewayLoadDistributionPolicyInformer) Lister() v1beta1.AzureApplicationGatewayLoadDistributionPolicyLister {
	return v1beta1.NewAzureApplicationGatewayLoadDistributionPolicyLister(f.Informer().GetIndexer())
}
