/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/globalservice/v1alpha1"
	scheme "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/azure_multicluster_crd_client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GlobalServicesGetter has a method to return a GlobalServiceInterface.
// A group's client should implement this interface.
type GlobalServicesGetter interface {
	GlobalServices(namespace string) GlobalServiceInterface
}

// GlobalServiceInterface has methods to work with GlobalService resources.
type GlobalServiceInterface interface {
	Create(ctx context.Context, globalService *v1alpha1.GlobalService, opts v1.CreateOptions) (*v1alpha1.GlobalService, error)
	Update(ctx context.Context, globalService *v1alpha1.GlobalService, opts v1.UpdateOptions) (*v1alpha1.GlobalService, error)
	UpdateStatus(ctx context.Context, globalService *v1alpha1.GlobalService, opts v1.UpdateOptions) (*v1alpha1.GlobalService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GlobalService, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GlobalServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlobalService, err error)
	GlobalServiceExpansion
}

// globalServices implements GlobalServiceInterface
type globalServices struct {
	client rest.Interface
	ns     string
}

// newGlobalServices returns a GlobalServices
func newGlobalServices(c *AzureglobalservicesV1alpha1Client, namespace string) *globalServices {
	return &globalServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the globalService, and returns the corresponding globalService object, and an error if there is any.
func (c *globalServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GlobalService, err error) {
	result = &v1alpha1.GlobalService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("globalservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GlobalServices that match those selectors.
func (c *globalServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GlobalServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GlobalServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("globalservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested globalServices.
func (c *globalServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("globalservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a globalService and creates it.  Returns the server's representation of the globalService, and an error, if there is any.
func (c *globalServices) Create(ctx context.Context, globalService *v1alpha1.GlobalService, opts v1.CreateOptions) (result *v1alpha1.GlobalService, err error) {
	result = &v1alpha1.GlobalService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("globalservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalService).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a globalService and updates it. Returns the server's representation of the globalService, and an error, if there is any.
func (c *globalServices) Update(ctx context.Context, globalService *v1alpha1.GlobalService, opts v1.UpdateOptions) (result *v1alpha1.GlobalService, err error) {
	result = &v1alpha1.GlobalService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("globalservices").
		Name(globalService.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalService).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *globalServices) UpdateStatus(ctx context.Context, globalService *v1alpha1.GlobalService, opts v1.UpdateOptions) (result *v1alpha1.GlobalService, err error) {
	result = &v1alpha1.GlobalService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("globalservices").
		Name(globalService.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalService).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the globalService and deletes it. Returns an error if one occurs.
func (c *globalServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("globalservices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *globalServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("globalservices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched globalService.
func (c *globalServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlobalService, err error) {
	result = &v1alpha1.GlobalService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("globalservices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
