/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureapplicationgatewayloaddistributionpolicy/v1"
	scheme "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AzureApplicationGatewayLoadDistributionPoliciesGetter has a method to return a AzureApplicationGatewayLoadDistributionPolicyInterface.
// A group's client should implement this interface.
type AzureApplicationGatewayLoadDistributionPoliciesGetter interface {
	AzureApplicationGatewayLoadDistributionPolicies(namespace string) AzureApplicationGatewayLoadDistributionPolicyInterface
}

// AzureApplicationGatewayLoadDistributionPolicyInterface has methods to work with AzureApplicationGatewayLoadDistributionPolicy resources.
type AzureApplicationGatewayLoadDistributionPolicyInterface interface {
	Create(ctx context.Context, azureApplicationGatewayLoadDistributionPolicy *v1.AzureApplicationGatewayLoadDistributionPolicy, opts metav1.CreateOptions) (*v1.AzureApplicationGatewayLoadDistributionPolicy, error)
	Update(ctx context.Context, azureApplicationGatewayLoadDistributionPolicy *v1.AzureApplicationGatewayLoadDistributionPolicy, opts metav1.UpdateOptions) (*v1.AzureApplicationGatewayLoadDistributionPolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.AzureApplicationGatewayLoadDistributionPolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.AzureApplicationGatewayLoadDistributionPolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AzureApplicationGatewayLoadDistributionPolicy, err error)
	AzureApplicationGatewayLoadDistributionPolicyExpansion
}

// azureApplicationGatewayLoadDistributionPolicies implements AzureApplicationGatewayLoadDistributionPolicyInterface
type azureApplicationGatewayLoadDistributionPolicies struct {
	client rest.Interface
	ns     string
}

// newAzureApplicationGatewayLoadDistributionPolicies returns a AzureApplicationGatewayLoadDistributionPolicies
func newAzureApplicationGatewayLoadDistributionPolicies(c *AzureapplicationgatewayloaddistributionpolicyV1Client, namespace string) *azureApplicationGatewayLoadDistributionPolicies {
	return &azureApplicationGatewayLoadDistributionPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the azureApplicationGatewayLoadDistributionPolicy, and returns the corresponding azureApplicationGatewayLoadDistributionPolicy object, and an error if there is any.
func (c *azureApplicationGatewayLoadDistributionPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.AzureApplicationGatewayLoadDistributionPolicy, err error) {
	result = &v1.AzureApplicationGatewayLoadDistributionPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azureapplicationgatewayloaddistributionpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzureApplicationGatewayLoadDistributionPolicies that match those selectors.
func (c *azureApplicationGatewayLoadDistributionPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AzureApplicationGatewayLoadDistributionPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AzureApplicationGatewayLoadDistributionPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azureapplicationgatewayloaddistributionpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azureApplicationGatewayLoadDistributionPolicies.
func (c *azureApplicationGatewayLoadDistributionPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("azureapplicationgatewayloaddistributionpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a azureApplicationGatewayLoadDistributionPolicy and creates it.  Returns the server's representation of the azureApplicationGatewayLoadDistributionPolicy, and an error, if there is any.
func (c *azureApplicationGatewayLoadDistributionPolicies) Create(ctx context.Context, azureApplicationGatewayLoadDistributionPolicy *v1.AzureApplicationGatewayLoadDistributionPolicy, opts metav1.CreateOptions) (result *v1.AzureApplicationGatewayLoadDistributionPolicy, err error) {
	result = &v1.AzureApplicationGatewayLoadDistributionPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("azureapplicationgatewayloaddistributionpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azureApplicationGatewayLoadDistributionPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a azureApplicationGatewayLoadDistributionPolicy and updates it. Returns the server's representation of the azureApplicationGatewayLoadDistributionPolicy, and an error, if there is any.
func (c *azureApplicationGatewayLoadDistributionPolicies) Update(ctx context.Context, azureApplicationGatewayLoadDistributionPolicy *v1.AzureApplicationGatewayLoadDistributionPolicy, opts metav1.UpdateOptions) (result *v1.AzureApplicationGatewayLoadDistributionPolicy, err error) {
	result = &v1.AzureApplicationGatewayLoadDistributionPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azureapplicationgatewayloaddistributionpolicies").
		Name(azureApplicationGatewayLoadDistributionPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azureApplicationGatewayLoadDistributionPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the azureApplicationGatewayLoadDistributionPolicy and deletes it. Returns an error if one occurs.
func (c *azureApplicationGatewayLoadDistributionPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azureapplicationgatewayloaddistributionpolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azureApplicationGatewayLoadDistributionPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azureapplicationgatewayloaddistributionpolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched azureApplicationGatewayLoadDistributionPolicy.
func (c *azureApplicationGatewayLoadDistributionPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AzureApplicationGatewayLoadDistributionPolicy, err error) {
	result = &v1.AzureApplicationGatewayLoadDistributionPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("azureapplicationgatewayloaddistributionpolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
