# This contains common build steps

steps:
  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      shopt -s dotglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: "Set up the Go workspace"

  - task: HelmInstaller@1
    displayName: Helm installer
    inputs: 
      helmVersionToInstall: latest

  - script: make lint-all
    workingDirectory: "$(modulePath)"
    displayName: "Go and Helm lint check"

  - script: make vet-all
    workingDirectory: "$(modulePath)"
    displayName: "Go vet"

  - script: make build
    workingDirectory: "$(modulePath)"
    displayName: "Get dependencies and build"

  - script: make unittest
    workingDirectory: "$(modulePath)"
    displayName: "Run unit tests with code coverage"

  - task: PublishTestResults@2
    continueOnError: true
    condition: succeededOrFailed()
    inputs:
      failTaskOnFailedTests: true
      testRunner: JUnit
      testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml

  - task: PublishCodeCoverageResults@1
    continueOnError: true
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(modulePath)/coverage.xml
      reportDirectory: $(modulePath)/coverage

  - task: CopyFiles@2
    inputs:
      contents: |
        $(modulePath)/scripts/**
        $(modulePath)/helm/**
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: drop
