trigger:
  branches:
    include:
    - master
    - release/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  GOBIN:  '$(GOPATH)/bin'
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'
  GOOS: 'linux'
  GO111MODULE: 'on'
  GO_PROJ: 'github.com/Azure/$(build.repository.name)'

steps:
- template: build.yml
