apiVersion: v1
entries:
  ingress-azure:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-20T00:09:30.399414701-08:00
    description: Use Azure Application Gateway as the ingress for an Azure Kubernetes
      Service cluster.
    digest: 1255b1c15cca79c7ec722eeb338de202ee66e431c8790ed55108ffad4af4bbd9
    name: ingress-azure
    urls:
    - https://azure.github.io/application-gateway-kubernetes-ingress/helm/ingress-azure-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-20T00:09:30.398967367-08:00
    description: Use Azure Application Gateway as the ingress for an Azure Kubernetes
      Service cluster.
    digest: 39cc6e0c535835667fd26f609a56daf32d31f6a256811a93ee04e265b1bb7216
    name: ingress-azure
    urls:
    - https://azure.github.io/application-gateway-kubernetes-ingress/helm/ingress-azure-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-20T00:09:30.39838928-08:00
    description: Use Azure Application Gateway as the ingress for an Azure Kubernetes
      Service cluster.
    digest: 643f5b99c847952108e781ce746f27bed55b248a002ee04b6b6ca3f0b51320ba
    name: ingress-azure
    urls:
    - https://azure.github.io/application-gateway-kubernetes-ingress/helm/ingress-azure-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-20T00:09:30.39778173-08:00
    description: Use Azure Application Gateway as the ingress for an Azure Kubernetes
      Service cluster.
    digest: 9664986a6affd3487d5a41772c7e92b23d79693e89d37143e094fec0fbcec1c2
    name: ingress-azure
    urls:
    - https://azure.github.io/application-gateway-kubernetes-ingress/helm/ingress-azure-0.1.2.tgz
    version: 0.1.2
generated: 2018-11-20T00:09:30.395394225-08:00
