/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/loaddistributionpolicy/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLoadDistributionPolicies implements LoadDistributionPolicyInterface
type FakeLoadDistributionPolicies struct {
	Fake *FakeLoaddistributionpoliciesV1beta1
	ns   string
}

var loaddistributionpoliciesResource = schema.GroupVersionResource{Group: "loaddistributionpolicies.appgw.ingress.azure.io", Version: "v1beta1", Resource: "loaddistributionpolicies"}

var loaddistributionpoliciesKind = schema.GroupVersionKind{Group: "loaddistributionpolicies.appgw.ingress.azure.io", Version: "v1beta1", Kind: "LoadDistributionPolicy"}

// Get takes name of the loadDistributionPolicy, and returns the corresponding loadDistributionPolicy object, and an error if there is any.
func (c *FakeLoadDistributionPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.LoadDistributionPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(loaddistributionpoliciesResource, c.ns, name), &v1beta1.LoadDistributionPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LoadDistributionPolicy), err
}

// List takes label and field selectors, and returns the list of LoadDistributionPolicies that match those selectors.
func (c *FakeLoadDistributionPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.LoadDistributionPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(loaddistributionpoliciesResource, loaddistributionpoliciesKind, c.ns, opts), &v1beta1.LoadDistributionPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.LoadDistributionPolicyList{ListMeta: obj.(*v1beta1.LoadDistributionPolicyList).ListMeta}
	for _, item := range obj.(*v1beta1.LoadDistributionPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested loadDistributionPolicies.
func (c *FakeLoadDistributionPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(loaddistributionpoliciesResource, c.ns, opts))

}

// Create takes the representation of a loadDistributionPolicy and creates it.  Returns the server's representation of the loadDistributionPolicy, and an error, if there is any.
func (c *FakeLoadDistributionPolicies) Create(ctx context.Context, loadDistributionPolicy *v1beta1.LoadDistributionPolicy, opts v1.CreateOptions) (result *v1beta1.LoadDistributionPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(loaddistributionpoliciesResource, c.ns, loadDistributionPolicy), &v1beta1.LoadDistributionPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LoadDistributionPolicy), err
}

// Update takes the representation of a loadDistributionPolicy and updates it. Returns the server's representation of the loadDistributionPolicy, and an error, if there is any.
func (c *FakeLoadDistributionPolicies) Update(ctx context.Context, loadDistributionPolicy *v1beta1.LoadDistributionPolicy, opts v1.UpdateOptions) (result *v1beta1.LoadDistributionPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(loaddistributionpoliciesResource, c.ns, loadDistributionPolicy), &v1beta1.LoadDistributionPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LoadDistributionPolicy), err
}

// Delete takes name of the loadDistributionPolicy and deletes it. Returns an error if one occurs.
func (c *FakeLoadDistributionPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(loaddistributionpoliciesResource, c.ns, name), &v1beta1.LoadDistributionPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLoadDistributionPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(loaddistributionpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.LoadDistributionPolicyList{})
	return err
}

// Patch applies the patch and returns the patched loadDistributionPolicy.
func (c *FakeLoadDistributionPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.LoadDistributionPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(loaddistributionpoliciesResource, c.ns, name, pt, data, subresources...), &v1beta1.LoadDistributionPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LoadDistributionPolicy), err
}
