/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureingressmanagedtarget/v1"
	scheme "github.com/Azure/application-gateway-kubernetes-ingress/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AzureIngressManagedTargetsGetter has a method to return a AzureIngressManagedTargetInterface.
// A group's client should implement this interface.
type AzureIngressManagedTargetsGetter interface {
	AzureIngressManagedTargets(namespace string) AzureIngressManagedTargetInterface
}

// AzureIngressManagedTargetInterface has methods to work with AzureIngressManagedTarget resources.
type AzureIngressManagedTargetInterface interface {
	Create(*v1.AzureIngressManagedTarget) (*v1.AzureIngressManagedTarget, error)
	Update(*v1.AzureIngressManagedTarget) (*v1.AzureIngressManagedTarget, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.AzureIngressManagedTarget, error)
	List(opts metav1.ListOptions) (*v1.AzureIngressManagedTargetList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AzureIngressManagedTarget, err error)
	AzureIngressManagedTargetExpansion
}

// azureIngressManagedTargets implements AzureIngressManagedTargetInterface
type azureIngressManagedTargets struct {
	client rest.Interface
	ns     string
}

// newAzureIngressManagedTargets returns a AzureIngressManagedTargets
func newAzureIngressManagedTargets(c *AzureingressmanagedtargetsV1Client, namespace string) *azureIngressManagedTargets {
	return &azureIngressManagedTargets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the azureIngressManagedTarget, and returns the corresponding azureIngressManagedTarget object, and an error if there is any.
func (c *azureIngressManagedTargets) Get(name string, options metav1.GetOptions) (result *v1.AzureIngressManagedTarget, err error) {
	result = &v1.AzureIngressManagedTarget{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azureingressmanagedtargets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzureIngressManagedTargets that match those selectors.
func (c *azureIngressManagedTargets) List(opts metav1.ListOptions) (result *v1.AzureIngressManagedTargetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AzureIngressManagedTargetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azureingressmanagedtargets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azureIngressManagedTargets.
func (c *azureIngressManagedTargets) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("azureingressmanagedtargets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a azureIngressManagedTarget and creates it.  Returns the server's representation of the azureIngressManagedTarget, and an error, if there is any.
func (c *azureIngressManagedTargets) Create(azureIngressManagedTarget *v1.AzureIngressManagedTarget) (result *v1.AzureIngressManagedTarget, err error) {
	result = &v1.AzureIngressManagedTarget{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("azureingressmanagedtargets").
		Body(azureIngressManagedTarget).
		Do().
		Into(result)
	return
}

// Update takes the representation of a azureIngressManagedTarget and updates it. Returns the server's representation of the azureIngressManagedTarget, and an error, if there is any.
func (c *azureIngressManagedTargets) Update(azureIngressManagedTarget *v1.AzureIngressManagedTarget) (result *v1.AzureIngressManagedTarget, err error) {
	result = &v1.AzureIngressManagedTarget{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azureingressmanagedtargets").
		Name(azureIngressManagedTarget.Name).
		Body(azureIngressManagedTarget).
		Do().
		Into(result)
	return
}

// Delete takes name of the azureIngressManagedTarget and deletes it. Returns an error if one occurs.
func (c *azureIngressManagedTargets) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azureingressmanagedtargets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azureIngressManagedTargets) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azureingressmanagedtargets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched azureIngressManagedTarget.
func (c *azureIngressManagedTargets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AzureIngressManagedTarget, err error) {
	result = &v1.AzureIngressManagedTarget{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("azureingressmanagedtargets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
